package com.xorbix.loopdeck.editor.photoeditor

enum class PhotoFilter {
    None, AUTO_FIX, BLACK_WHITE, BRIGHTNESS, CONTRAST, Cross, DOCUMENTARY, DUE_TONE, FILL_LIGHT, FISH_EYE, FLIP_VERTICAL, Flip, GRAIN, GRAY_SCALE, LOMISH, NEGATIVE, POSTERIZE, ROTATE, SATURATE, SEPIA, SHARPEN, TEMPERATURE, TINT, VIGNETTE
}